chore: Pre-build DevWorkspace templates for devfile v2
redhat-developer/codeready-workspaces-images pull request #156
Opened 2021-12-14 15:19 UTC by vinokurig

2021-12-14 15:25 UTC, nickboldt commented on codeready-workspaces-devfileregistry/build/scripts/clone_and_zip.sh
> +# Copyright (c) 2018-2021 Red Hat, Inc.
copyright date is wrong

2021-12-14 15:27 UTC, nickboldt commented on codeready-workspaces-devfileregistry/build/scripts/clone_and_zip.sh
> +TEMP_REPO="/tmp/cloned"
you could use a unique folder each time to avoid the chance of ever colliding when running in a loop... 

```
$➔ TEMP_REPO=$(mktemp -d); cd $TEMP_REPO

/tmp/tmp.L1tZk40One
```

2021-12-14 15:30 UTC, nickboldt commented on codeready-workspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh
> +    --output-file:"${dir}"/devworkspace-che-theia-next.yaml \
do we need both latest and next in CRW?

2021-12-16 17:42 UTC, nickboldt commented
by the way some of this change might have to also be done in upstream repo https://github.com/redhat-developer/codeready-workspaces/tree/crw-2-rhel-8/dependencies/che-devfile-registry and then synched to this midstream repo using the sync.sh script.

2021-12-20 08:53 UTC, vinokurig commented on codeready-workspaces-devfileregistry/build/scripts/clone_and_zip.sh
> +# Copyright (c) 2018-2021 Red Hat, Inc.
It is the same as most `sh` script header headers. What it should be?

2021-12-20 14:44 UTC, vinokurig commented on codeready-workspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh
> +    --output-file:"${dir}"/devworkspace-che-theia-next.yaml \
Could you please elaborate on this more

2021-12-20 14:46 UTC, vinokurig commented on codeready-workspaces-devfileregistry/build/scripts/clone_and_zip.sh
> +TEMP_REPO="/tmp/cloned"
done

2021-12-20 15:11 UTC, nickboldt commented on codeready-workspaces-devfileregistry/build/scripts/clone_and_zip.sh
> +# Copyright (c) 2018-2021 Red Hat, Inc.
if file created in 2021, then copyright starts in 2021. Not 2018.

2021-12-20 15:12 UTC, nickboldt commented on codeready-workspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh
> +    --output-file:"${dir}"/devworkspace-che-theia-next.yaml \
I'm trying to understand why we ned to build a theia-next and a theia-latest.

2021-12-20 16:53 UTC, vinokurig commented on codeready-workspaces-devfileregistry/build/scripts/clone_and_zip.sh
> +# Copyright (c) 2018-2021 Red Hat, Inc.
done

2021-12-20 17:38 UTC, vinokurig commented on codeready-workspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh
> +    --output-file:"${dir}"/devworkspace-che-theia-next.yaml \
It comes from the discussion here https://github.com/eclipse-che/che-devfile-registry/pull/518#issuecomment-976449362

2021-12-21 15:15 UTC, svor commented on codeready-workspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh
> +    --output-file:"${dir}"/devworkspace-che-theia-next.yaml \
maybe for CRW it is enough to have only latest, like we do for editors: https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/che-editors.yaml#L5

2021-12-21 16:45 UTC, nickboldt commented on codeready-workspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh
> +    --output-file:"${dir}"/devworkspace-che-theia-next.yaml \
how is next even used? seems like for the product there's no way to switch on theia next vs. using theia latest.

2021-12-22 13:40 UTC, vinokurig commented on codeready-workspaces-devfileregistry/build/scripts/generate_devworkspace_templates.sh
> +    --output-file:"${dir}"/devworkspace-che-theia-next.yaml \
Removed the generation of `devworkspace-che-theia-next.yaml`

2021-12-23 15:03 UTC, nickboldt requested changes
need updates to [build/scripts/sync.sh](https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-devfileregistry/build/scripts/sync.sh) script as noted in https://github.com/redhat-developer/codeready-workspaces/pull/652#issuecomment-999686702

2022-01-10 16:00 UTC, nickboldt commented
> need updates to [build/scripts/sync.sh](https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-devfileregistry/build/scripts/sync.sh) script as noted in [redhat-developer/codeready-workspaces#652 (comment)](https://github.com/redhat-developer/codeready-workspaces/pull/652#issuecomment-999686702)

Still need sync script to be updated. Airgap support == can't rely on surge.sh

2022-01-31 22:08 UTC, nickboldt commented
This PR is now outdated compared to https://github.com/redhat-developer/codeready-workspaces/pull/652/files and since that one should produce files which are synced from the crw to crw-images repo anyway, we likely don't need this PR.

Therefore closing.

2022-01-31 22:08 UTC, closed without merging