chore: check for python-related directories existence when starting the UDI
redhat-developer/codeready-workspaces-images pull request #189
Opened 2022-02-16 16:06 UTC by vitaliy-guliy

Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

Fixes failing the container startup when python-related directories don't exist.

2022-02-16 16:34 UTC, nickboldt requested changes
> I've checked it works with java, but cannot say anything about python

wouldn't it make sense to try it with a python devfile since this change could impact python ?

since the udi image should have python installed, these shouldn't fail... right? Or are they only created SOMETIMES if the devfile enables python lang server?

2022-02-16 16:57 UTC, vitaliy-guliy commented
> > I've checked it works with java, but cannot say anything about python
> 
> wouldn't it make sense to try it with a python devfile since this change could impact python ?

why not? I think the container should be working for all kind of projects.

> since the udi image should have python installed, these shouldn't fail... right? Or are they only created SOMETIMES if the devfile enables python lang server?

`.venv-tmp` dir is created while installing python language server https://github.com/vitaliy-guliy/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-udi/Dockerfile#L128
If the language server ins missing, it should not fail the container.

The error is not related on the devfile. When I try to run the container locally, I have the following output
```
$ docker run -ti quay.io/crw/udi-rhel8:2.16 bash
/home/user/.venv is empty, moving files from /home/user/.venv-tmp/
mv: cannot stat '/home/user/.venv-tmp/*': No such file or directory
```

2022-02-16 17:00 UTC, nickboldt commented
The actual error is a docker warning, `warning: Unknown instruction: LN`.

Should be fixed with https://github.com/redhat-developer/codeready-workspaces-images/commit/e96260ff092c7ae6c4704e3202ae9784b8b7797f#diff-488be4ea29f3b560e941ca90c8ec75f32705e5a35e9aa4b3a4545a6ed5f68c03R115

Respinning: https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/CRW_CI/job/sync-to-downstream_2.x/3922/

2022-02-16 17:12 UTC, vitaliy-guliy commented
> The actual error is a docker warning, `warning: Unknown instruction: LN`.
> 
> Should be fixed with [e96260f#diff-488be4ea29f3b560e941ca90c8ec75f32705e5a35e9aa4b3a4545a6ed5f68c03R115](https://github.com/redhat-developer/codeready-workspaces-images/commit/e96260ff092c7ae6c4704e3202ae9784b8b7797f#diff-488be4ea29f3b560e941ca90c8ec75f32705e5a35e9aa4b3a4545a6ed5f68c03R115)

It's not clear for me how it fixes the issue with python.

2022-02-16 17:49 UTC, nickboldt commented
> It's not clear for me how it fixes the issue with python.

Docker doesn't know what `LN` is. Because the previous line was missing a `&& \`. 

My fix should rejoin the lines so the install actually happens

2022-02-16 17:55 UTC, vitaliy-guliy commented
> 



> > It's not clear for me how it fixes the issue with python.
> 
> Docker doesn't know what `LN` is. Because the previous line was missing a `&& \`.
> 
> My fix should rejoin the lines so the install actually happens

Wouldn't it be nice to have that check in `entrypoint.sh` as well?

2022-02-16 19:07 UTC, nickboldt commented
> Wouldn't it be nice to have that check in entrypoint.sh as well?

maybe, but if we are supposed to have the python venv set up correctly, then entrypoint.sh should FAIL if python isn't configured, not just skip over it.

2022-02-17 03:18 UTC, nickboldt commented
After my fix:

```
$➔ docker run -ti quay.io/crw/udi-rhel8:2.16 bash
Unable to find image 'quay.io/crw/udi-rhel8:2.16' locally
2.16: Pulling from crw/udi-rhel8
...
Status: Downloaded newer image for quay.io/crw/udi-rhel8:2.16
/home/user/.venv is empty, moving files from /home/user/.venv-tmp/
(.venv) exit
exit
```

2022-02-17 08:53 UTC, svor commented on codeready-workspaces-udi/etc/entrypoint.sh
> +    mv "${HOME}"/.venv-tmp/* "${HOME}"/.venv
probably questions to @SDawley:
 
1. "${HOME}"/.venv is empty every time, it was just created in line 40 why do we need 
`if [ ! -f "${HOME}"/.venv/bin/activate ]; then`

2. why do we copy files in entrypoint.sh? 
This operation takes to much time and it makes the workspace starting a bit longer.
Why don't we have it in Dockerfile, then it will happen in build time?
```
mkdir -p "${HOME}"/.venv
mv "${HOME}"/.venv-tmp/* "${HOME}"/.venv
rm -rf "${HOME}"/.venv-tmp
```

2022-02-17 10:46 UTC, vitaliy-guliy commented on codeready-workspaces-udi/etc/entrypoint.sh
> +    mv "${HOME}"/.venv-tmp/* "${HOME}"/.venv
Let me give you an answer.
1. It's not a bid deal if we check for `"${HOME}"/.venv/bin/activate`. `mkdir -p "${HOME}"/.venv` does nothing if the directory is already exists.
2. Copying of files takes 53 seconds when I run the container locally. It's too much.
@nickboldt why not to do everything, that is needed when building the image? It would be nice to add few instructions inside Dockerfile, instead of having them in `entrypoint.sh`.

2022-02-17 13:10 UTC, vitaliy-guliy commented on codeready-workspaces-udi/etc/entrypoint.sh
> +    mv "${HOME}"/.venv-tmp/* "${HOME}"/.venv
I've prepared another one PR with improvement https://github.com/redhat-developer/codeready-workspaces-images/pull/190

2022-02-17 13:19 UTC, vitaliy-guliy commented
Persisted by https://github.com/redhat-developer/codeready-workspaces-images/pull/190

2022-02-17 13:19 UTC, closed without merging